BATCH_SIZE = 32
LEARNING_RATE = 0.01
EPSILON = 0.9
GAMMA = 0.9

SLOTPARA = {'item':1, 'brand':2, 'color':3, 'price':4}
EFFECTPARA = {"均勻膚色": 37,"深層清潔": 51,"薄透": 14,"控油": 42,"保濕": 5,"抗皺": 39,"抗氧化": 27,"不致痘": 66,"好推勻": 21,"亮澤": 53,"修正膚色": 11,"舒緩": 28,"細緻毛孔": 33,"服貼": 35,"淡斑": 49,"果凍色": 77,"修飾毛孔": 9,"修護": 7,"抗空汙": 68,"纖長": 18,"遮瑕": 10,"細緻": 22,"不致粉刺": 67,"溫和低刺激": 47,"捲翹": 58,"去角質": 50,"改善紋路": 70,"抗痘": 64,"緊實": 31,"光澤": 36,"霧面": 55,"好吸收": 48,"飽和色": 75,"美白": 24,"濃密": 59,"平滑膚觸": 26,"亮面": 56,"顯色": 20,"抗暈染": 17,"光滑": 71,"豐盈": 63,"漆亮感": 76,"潤色": 8,"快乾": 73,"防油": 54,"長效持妝": 13,"卸妝": 44,"抗屑": 78,"提升光澤": 25,"根根分明": 19,"預防落髮": 74,"收斂毛孔": 57,"透亮": 12,"香氛": 34,"珠光": 43,"防水": 45,"滋潤": 6,"防曬": 38,"色彩飽和": 16,"清潔": 41,"柔順": 52,"護色": 72,"溫水可卸": 61,"清爽": 29,"改善細紋": 40,"修容": 23,"抗老": 30,"拉提": 32,"不黏膩": 46,"好上色": 15,"打亮": 60,"改善粉刺": 65,"強韌髮絲": 62,"改善水腫": 69}

MAXTURNS = 7
N_STATES = 10
N_ACTIONS = 523
N_CANDIDATES = 200
N_SLOTS = len(SLOTPARA) + len(EFFECTPARA)         # effect
N_FEATURES = 4          # item, brand, color, effect
DIM_STATES = N_SLOTS

ANSWER = 0
RECOMMEND = 1
REQUEST = 0
YES = 1
NO = 0

# slot
ITEM = 1
BRAND = 2
COLOR = 3
PRICE = 4
EFFECT1 = 5
EFFECT2 = 6

R_SUCCESS = 100     # reward setting
R_FAIL = 100        # -2000
R_WRONG = -100000
R_NONE = -1

ITEMLIST = [
    "唇膏",
    "妝前打底",
    "氣墊粉餅",
    "BB霜",
    "CC霜",
    "粉餅",
    "腮紅修容",
    "粉底液",
    "粉條",
    "粉霜",
    "蜜粉",
    "遮瑕",
    "眉彩",
    "睫毛膏",
    "眼影",
    "眼線",
    "唇彩唇蜜",
    "唇筆",
    "保養面膜",
    "化妝水",
    "乳液",
    "乳霜",
    "凝膠凝凍",
    "精華液",
    "洗顏產品",
    "卸妝產品",
    "防曬隔離",
    "眼唇卸妝",
    "精華油",
    "保濕噴霧",
    "清潔面膜",
    "臉部去角質",
    "唇部保養",
    "眼部保養",
    "前導保養"
]

STATEDICT = {
    'request':0,
    'greeting':1, 'search_item': 2, 'inform':3,'react': 4,
    'noidea':5, 'chat': 6
}

ACTIONTABLE = ['answer','recommend_item',   # 0,1
        'greeting','ask_slot_item',         # 2,3
        'ask_slot_brand','ask_slot_color',  # 4,5
        'ask_slot_price','ask_slot_effect', # 6,7
        'praise_item','praise_user_choose', # 8,9
        'praise_user','show_comment',       # 10,11
        'chat', 'ok',                    # 12,13
        'recommend_slot_item_唇膏', 'recommend_slot_item_妝前打底', 'recommend_slot_item_氣墊粉餅', 'recommend_slot_item_BB霜', 'recommend_slot_item_CC霜', 'recommend_slot_item_粉餅', 'recommend_slot_item_腮紅修容', 'recommend_slot_item_粉底液', 'recommend_slot_item_粉條', 'recommend_slot_item_粉霜', 'recommend_slot_item_蜜粉', 'recommend_slot_item_遮瑕', 'recommend_slot_item_眉彩', 'recommend_slot_item_睫毛膏', 'recommend_slot_item_眼影', 'recommend_slot_item_眼線', 'recommend_slot_item_唇彩唇蜜', 'recommend_slot_item_唇筆', 'recommend_slot_item_保養面膜', 'recommend_slot_item_化妝水', 'recommend_slot_item_乳液', 'recommend_slot_item_乳霜', 'recommend_slot_item_凝膠凝凍', 'recommend_slot_item_精華液', 'recommend_slot_item_洗顏產品', 'recommend_slot_item_卸妝產品', 'recommend_slot_item_防曬隔離', 'recommend_slot_item_眼唇卸妝', 'recommend_slot_item_精華油', 'recommend_slot_item_保濕噴霧', 'recommend_slot_item_清潔面膜', 'recommend_slot_item_臉部去角質', 'recommend_slot_item_唇部保養', 'recommend_slot_item_眼部保養', 'recommend_slot_item_前導保養',
        "recommend_slot_brand_missha","recommend_slot_brand_hadalabo肌研","recommend_slot_brand_gatsby","recommend_slot_brand_brand1028","recommend_slot_brand_moroccanoil","recommend_slot_brand_espoir","recommend_slot_brand_dermaction","recommend_slot_brand_forbelovedgirl寵愛女孩","recommend_slot_brand_thecucumber廣源良","recommend_slot_brand_heme","recommend_slot_brand_media媚點","recommend_slot_brand_johnmastersorganics","recommend_slot_brand_ettusais艾杜紗","recommend_slot_brand_premier","recommend_slot_brand_西班牙babaria","recommend_slot_brand_tky","recommend_slot_brand_esprique","recommend_slot_brand_covermark","recommend_slot_brand_brand3m","recommend_slot_brand_frusirnana美膚娜娜","recommend_slot_brand_himalaya喜瑪拉雅","recommend_slot_brand_mayskin優若美","recommend_slot_brand_elemis","recommend_slot_brand_fashionkbeauty","recommend_slot_brand_aroa","recommend_slot_brand_nivea妮維雅","recommend_slot_brand_pinkgogirlhey蘋果肌女孩","recommend_slot_brand_voodoo","recommend_slot_brand_yourheart","recommend_slot_brand_uriage優麗雅","recommend_slot_brand_wondercore","recommend_slot_brand_corsica科皙佳","recommend_slot_brand_kamill","recommend_slot_brand_hacci","recommend_slot_brand_calvinklein","recommend_slot_brand_dermedic","recommend_slot_brand_drmorita","recommend_slot_brand_clinique倩碧","recommend_slot_brand_natracare","recommend_slot_brand_muji無印良品","recommend_slot_brand_chapex喬沛詩","recommend_slot_brand_petalfresh沛特斯","recommend_slot_brand_俏佳人","recommend_slot_brand_ren","recommend_slot_brand_absolution","recommend_slot_brand_sisley希思黎","recommend_slot_brand_laneige蘭芝","recommend_slot_brand_point","recommend_slot_brand_aveda肯夢","recommend_slot_brand_grainedepastel","recommend_slot_brand_crabtreeevelyn瑰珀翠","recommend_slot_brand_innerskin","recommend_slot_brand_jillstuart吉麗絲朵","recommend_slot_brand_grownalchemist","recommend_slot_brand_kbeauty","recommend_slot_brand_listwistea","recommend_slot_brand_guerlain嬌蘭","recommend_slot_brand_drjart","recommend_slot_brand_avene雅漾","recommend_slot_brand_forencos","recommend_slot_brand_ghosttowash","recommend_slot_brand_majolicamajorca戀愛魔鏡","recommend_slot_brand_miumiu","recommend_slot_brand_animecosme","recommend_slot_brand_cetaphil舒特膚","recommend_slot_brand_kosecosmeport蔻絲魅寶","recommend_slot_brand_becupidon邱比特","recommend_slot_brand_mote","recommend_slot_brand_aloederma璦露德瑪","recommend_slot_brand_tszjitsuei瓷肌萃","recommend_slot_brand_carmax小蜜媞","recommend_slot_brand_laformule法國植萃合度","recommend_slot_brand_purepawpaw","recommend_slot_brand_uka","recommend_slot_brand_skii","recommend_slot_brand_youbest優倍多","recommend_slot_brand_purebeauty","recommend_slot_brand_bvlgari寶格麗","recommend_slot_brand_neom","recommend_slot_brand_御泥坊","recommend_slot_brand_bondiwash","recommend_slot_brand_bobbibrown芭比布朗","recommend_slot_brand_diptyque","recommend_slot_brand_mio","recommend_slot_brand_sebamed施巴","recommend_slot_brand_zeynabear","recommend_slot_brand_becca","recommend_slot_brand_numismed樂美思","recommend_slot_brand_white","recommend_slot_brand_prettiean法國雅姿麗","recommend_slot_brand_innisfree","recommend_slot_brand_neuve惹我","recommend_slot_brand_50惠","recommend_slot_brand_clearturn","recommend_slot_brand_aesop","recommend_slot_brand_aprilskin","recommend_slot_brand_perlabella義貝拉","recommend_slot_brand_clarins克蘭詩","recommend_slot_brand_專科","recommend_slot_brand_shuuemura植村秀","recommend_slot_brand_thefaceshop菲詩小舖","recommend_slot_brand_mac","recommend_slot_brand_divinia蒂芬妮亞","recommend_slot_brand_bellabeauty","recommend_slot_brand_institutkariteparis巴黎乳油木","recommend_slot_brand_chicaychico","recommend_slot_brand_decorte黛珂","recommend_slot_brand_srbeauty","recommend_slot_brand_banilaco","recommend_slot_brand_countrystream","recommend_slot_brand_chanel香奈兒","recommend_slot_brand_080","recommend_slot_brand_kate凱婷","recommend_slot_brand_byterry","recommend_slot_brand_caudalie","recommend_slot_brand_shiseido資生堂","recommend_slot_brand_jurlique茱莉蔻","recommend_slot_brand_palmers帕瑪氏","recommend_slot_brand_biooil百洛","recommend_slot_brand_bonvivant","recommend_slot_brand_beyond","recommend_slot_brand_bevyc妝前保養","recommend_slot_brand_whoo后","recommend_slot_brand_drorganic","recommend_slot_brand_garnier卡尼爾","recommend_slot_brand_lesmerveilleusesladuree","recommend_slot_brand_我的美麗日記","recommend_slot_brand_neogence霓淨思","recommend_slot_brand_prada","recommend_slot_brand_azplaza","recommend_slot_brand_aderma艾芙美","recommend_slot_brand_dejavu","recommend_slot_brand_tsubaki思波綺","recommend_slot_brand_philips飛利浦","recommend_slot_brand_chronoaffection時間寵愛","recommend_slot_brand_fromnature","recommend_slot_brand_rmk","recommend_slot_brand_lorealparis巴黎萊雅","recommend_slot_brand_fancl","recommend_slot_brand_dove多芬","recommend_slot_brand_bionike","recommend_slot_brand_giorgioarmani亞曼尼","recommend_slot_brand_once","recommend_slot_brand_chlitina克麗緹娜","recommend_slot_brand_claires格麗","recommend_slot_brand_renefurterer荷那法蕊","recommend_slot_brand_unt","recommend_slot_brand_skinbiotec肌研生醫","recommend_slot_brand_dkny","recommend_slot_brand_ibl依必朗","recommend_slot_brand_melvita蜜葳特","recommend_slot_brand_curel珂潤","recommend_slot_brand_sofina蘇菲娜","recommend_slot_brand_neutrogena露得清","recommend_slot_brand_myscheming我的心機","recommend_slot_brand_essence","recommend_slot_brand_hopegirl","recommend_slot_brand_cellina雪芙蘭","recommend_slot_brand_evolu艾芙洛","recommend_slot_brand_jingcheng京城之霜","recommend_slot_brand_loccitane歐舒丹","recommend_slot_brand_hupanique涵沛","recommend_slot_brand_givenchy紀梵希","recommend_slot_brand_hadalabo","recommend_slot_brand_kryolan歌劇魅影","recommend_slot_brand_azlb","recommend_slot_brand_thebodyshop美體小舖","recommend_slot_brand_dhc","recommend_slot_brand_lalique","recommend_slot_brand_megustame美愛美","recommend_slot_brand_ponds旁氏","recommend_slot_brand_bioderma法國貝德瑪","recommend_slot_brand_whiteformula自白肌","recommend_slot_brand_tommyhilfiger","recommend_slot_brand_cnplaboratory","recommend_slot_brand_sweetheartbeauty甜心美妝","recommend_slot_brand_makeupforever","recommend_slot_brand_clarisonic科萊麗","recommend_slot_brand_dior迪奧","recommend_slot_brand_kiehls契爾氏","recommend_slot_brand_annasui安娜蘇","recommend_slot_brand_integrate絕色魅癮","recommend_slot_brand_smithcult","recommend_slot_brand_3ce","recommend_slot_brand_orbis","recommend_slot_brand_mdmmd明洞國際","recommend_slot_brand_sabon","recommend_slot_brand_drbronners布朗博士","recommend_slot_brand_goat","recommend_slot_brand_conibeauty","recommend_slot_brand_stclare聖克萊爾","recommend_slot_brand_tsaio上山採藥","recommend_slot_brand_hikaru喜凱露","recommend_slot_brand_targetprobywatsons","recommend_slot_brand_webner葦柏納","recommend_slot_brand_pauljoe","recommend_slot_brand_skinadvanced","recommend_slot_brand_dcs","recommend_slot_brand_revive麗膚再生","recommend_slot_brand_erborian艾博妍","recommend_slot_brand_apieu","recommend_slot_brand_ampmskincare","recommend_slot_brand_freshel膚蕊","recommend_slot_brand_aqualabel水之印","recommend_slot_brand_chicchoc奇可俏可","recommend_slot_brand_suqqu","recommend_slot_brand_kanebo佳麗寶","recommend_slot_brand_美舒律","recommend_slot_brand_drhsieh達特醫","recommend_slot_brand_eos伊歐詩","recommend_slot_brand_kose高絲","recommend_slot_brand_chateaulabiotte","recommend_slot_brand_vancleefarpels梵克雅寶","recommend_slot_brand_nars","recommend_slot_brand_olay歐蕾","recommend_slot_brand_animecosme","recommend_slot_brand_jomalonelondon","recommend_slot_brand_malingoetz","recommend_slot_brand_omorovicza","recommend_slot_brand_fititwhitia","recommend_slot_brand_labseries雅男士","recommend_slot_brand_paltac","recommend_slot_brand_drsatin","recommend_slot_brand_panatec沛莉緹","recommend_slot_brand_za","recommend_slot_brand_eyeko","recommend_slot_brand_cota","recommend_slot_brand_avalon","recommend_slot_brand_bioessence碧歐斯","recommend_slot_brand_biotherm碧兒泉","recommend_slot_brand_johnsons嬌生","recommend_slot_brand_canmake","recommend_slot_brand_loveways羅崴詩","recommend_slot_brand_larocheposay理膚寶水","recommend_slot_brand_uno","recommend_slot_brand_freshline","recommend_slot_brand_equilibra義貝拉","recommend_slot_brand_tonymoly","recommend_slot_brand_darphin朵法","recommend_slot_brand_sisterdiary姊妹日記","recommend_slot_brand_evita艾薇塔","recommend_slot_brand_dermaformula美肌醫生","recommend_slot_brand_memebox","recommend_slot_brand_cleanclear可伶可俐","recommend_slot_brand_evian愛維養","recommend_slot_brand_burberry","recommend_slot_brand_jumelle佐媚朵爾","recommend_slot_brand_chantecaille香緹卡","recommend_slot_brand_bbia","recommend_slot_brand_absolutenewyork絕色紐約","recommend_slot_brand_valentino范倫鐵諾","recommend_slot_brand_lauramercier蘿拉蜜思","recommend_slot_brand_dermalogica德卡","recommend_slot_brand_glamglow","recommend_slot_brand_reinachu日本蕾娜啾","recommend_slot_brand_法國歐德瑪","recommend_slot_brand_skinfood","recommend_slot_brand_奢華寶貝","recommend_slot_brand_toryburch","recommend_slot_brand_immeme","recommend_slot_brand_mori水漾膜麗","recommend_slot_brand_etudehouse","recommend_slot_brand_stives聖艾芙","recommend_slot_brand_toocoolforschool","recommend_slot_brand_lamer海洋拉娜","recommend_slot_brand_zbyziva","recommend_slot_brand_yuskin悠斯晶","recommend_slot_brand_iope","recommend_slot_brand_ipsa茵芙莎","recommend_slot_brand_derminstitute得因特","recommend_slot_brand_alterna","recommend_slot_brand_cezanne","recommend_slot_brand_rebeccabonbon","recommend_slot_brand_beautia倍立雅","recommend_slot_brand_naruko","recommend_slot_brand_laprairie","recommend_slot_brand_beautymate美肌之誌","recommend_slot_brand_marykay玫琳凱","recommend_slot_brand_azzeen芝妍","recommend_slot_brand_remeg潤美肌","recommend_slot_brand_skinlife滋卿愛","recommend_slot_brand_pure","recommend_slot_brand_teapower茶寶","recommend_slot_brand_thailandbirds泰國雙燕","recommend_slot_brand_nacola","recommend_slot_brand_kpalette","recommend_slot_brand_lpmediheal美迪惠爾","recommend_slot_brand_three","recommend_slot_brand_ludeya露蒂雅","recommend_slot_brand_etvos","recommend_slot_brand_revlon露華濃","recommend_slot_brand_maybelline媚比琳","recommend_slot_brand_rosyrosa","recommend_slot_brand_ponpon澎澎","recommend_slot_brand_origins品木宣言","recommend_slot_brand_drwu","recommend_slot_brand_cledepeaubeaute肌膚之鑰","recommend_slot_brand_forbelovedone寵愛之名","recommend_slot_brand_shelleyandteddy","recommend_slot_brand_lsy林三益","recommend_slot_brand_nealsyardremedies尼爾氏香芬庭園","recommend_slot_brand_facequeen絕世愛美肌","recommend_slot_brand_kissme奇士美","recommend_slot_brand_collagen","recommend_slot_brand_benefit","recommend_slot_brand_swissvita瑞士薇佳","recommend_slot_brand_elizabetharden伊麗莎白雅頓","recommend_slot_brand_dermal","recommend_slot_brand_puresmile","recommend_slot_brand_philosophy肌膚哲理","recommend_slot_brand_srichand喜簪","recommend_slot_brand_vdl","recommend_slot_brand_oguma水美媒","recommend_slot_brand_legere蘭吉兒","recommend_slot_brand_aromebywatsons","recommend_slot_brand_salvatoreferragamo","recommend_slot_brand_evelom","recommend_slot_brand_jericho","recommend_slot_brand_rodial","recommend_slot_brand_bourjois妙巴黎","recommend_slot_brand_syrio","recommend_slot_brand_naf","recommend_slot_brand_softymo絲芙蒂","recommend_slot_brand_solone","recommend_slot_brand_vichy薇姿","recommend_slot_brand_clio珂莉奧","recommend_slot_brand_peripera","recommend_slot_brand_albion艾倫比亞","recommend_slot_brand_phisoderm菲蘇德美","recommend_slot_brand_jone","recommend_slot_brand_sulwhasoo雪花秀","recommend_slot_brand_moonshot","recommend_slot_brand_aviva","recommend_slot_brand_kaideluxe型色大師","recommend_slot_brand_ernolaszlo奧倫納素","recommend_slot_brand_bifesta","recommend_slot_brand_beautybuffet天天美麗","recommend_slot_brand_burtsbees小蜜蜂爺爺","recommend_slot_brand_rudyprofumi","recommend_slot_brand_bonanza寶藝","recommend_slot_brand_beautymaker","recommend_slot_brand_domohornwrinkle朵茉麗蔻","recommend_slot_brand_watsonsskin屈臣氏","recommend_slot_brand_ysl聖羅蘭","recommend_slot_brand_mentholatum曼秀雷敦","recommend_slot_brand_ele","recommend_slot_brand_alkmene","recommend_slot_brand_rahua","recommend_slot_brand_mistine","recommend_slot_brand_harmony","recommend_slot_brand_nooni","recommend_slot_brand_klorane蔻蘿蘭","recommend_slot_brand_marcjacobs","recommend_slot_brand_valmont法兒曼","recommend_slot_brand_陽農園","recommend_slot_brand_benzac","recommend_slot_brand_revlis","recommend_slot_brand_versace凡賽斯","recommend_slot_brand_locherber樂凱博","recommend_slot_brand_mdnaskin","recommend_slot_brand_aatest測試","recommend_slot_brand_motives莫蒂膚","recommend_slot_brand_lululun","recommend_slot_brand_ryo呂","recommend_slot_brand_byredo","recommend_slot_brand_fasio菲希歐","recommend_slot_brand_lovecode","recommend_slot_brand_biore蜜妮","recommend_slot_brand_saugella賽吉兒","recommend_slot_brand_ninaricci","recommend_slot_brand_ponyeffect","recommend_slot_brand_vaseline凡士林","recommend_slot_brand_ayura東洋美學","recommend_slot_brand_neotec妮傲絲翠","recommend_slot_brand_misshana花娜小姐","recommend_slot_brand_thesaem","recommend_slot_brand_lb",
        'recommend_slot_color_橘色', 'recommend_slot_color_紅色', 'recommend_slot_color_酒紅色', 'recommend_slot_color_綠色', 'recommend_slot_color_藍色', 'recommend_slot_color_棕色', 'recommend_slot_color_黑色', 'recommend_slot_color_黃色', 'recommend_slot_color_紫色', 'recommend_slot_color_粉紅色', 'recommend_slot_color_淺棕色', 'recommend_slot_color_深棕色', 'recommend_slot_color_金色', 'recommend_slot_color_香檳色', 'recommend_slot_color_明亮膚色', 'recommend_slot_color_自然膚色', 'recommend_slot_color_玫瑰·', 'recommend_slot_color_大地色', 'recommend_slot_color_白皙膚色', 'recommend_slot_color_透明', 'recommend_slot_color_莓紅', 'recommend_slot_color_珊瑚', 'recommend_slot_color_桃紅', 'recommend_slot_color_健康膚色', 'recommend_slot_effect_保濕', 'recommend_slot_effect_滋潤', 'recommend_slot_effect_修護', 'recommend_slot_effect_潤色', 'recommend_slot_effect_修飾毛孔', 'recommend_slot_effect_遮瑕', 'recommend_slot_effect_修正膚色', 'recommend_slot_effect_透亮', 'recommend_slot_effect_長效持妝', 'recommend_slot_effect_薄透', 'recommend_slot_effect_好上色', 'recommend_slot_effect_色彩飽和', 'recommend_slot_effect_抗暈染', 'recommend_slot_effect_纖長', 'recommend_slot_effect_根根分明', 'recommend_slot_effect_顯色', 'recommend_slot_effect_好推勻', 'recommend_slot_effect_細緻', 'recommend_slot_effect_修容', 'recommend_slot_effect_美白', 'recommend_slot_effect_提升光澤', 'recommend_slot_effect_平滑膚觸', 'recommend_slot_effect_抗氧化', 'recommend_slot_effect_舒緩', 'recommend_slot_effect_清爽', 'recommend_slot_effect_抗老', 'recommend_slot_effect_緊實', 'recommend_slot_effect_拉提', 'recommend_slot_effect_細緻毛孔', 'recommend_slot_effect_香氛', 'recommend_slot_effect_服貼', 'recommend_slot_effect_光澤', 'recommend_slot_effect_均勻膚色', 'recommend_slot_effect_防曬', 'recommend_slot_effect_抗皺', 'recommend_slot_effect_改善細紋', 'recommend_slot_effect_清潔', 'recommend_slot_effect_控油', 'recommend_slot_effect_珠光', 'recommend_slot_effect_卸妝', 'recommend_slot_effect_防水', 'recommend_slot_effect_不黏膩', 'recommend_slot_effect_溫和低刺激', 'recommend_slot_effect_好吸收', 'recommend_slot_effect_淡斑', 'recommend_slot_effect_去角質', 'recommend_slot_effect_深層清潔', 'recommend_slot_effect_柔順', 'recommend_slot_effect_亮澤', 'recommend_slot_effect_防油', 'recommend_slot_effect_霧面', 'recommend_slot_effect_亮面', 'recommend_slot_effect_收斂毛孔', 'recommend_slot_effect_捲翹', 'recommend_slot_effect_濃密', 'recommend_slot_effect_打亮', 'recommend_slot_effect_溫水可卸', 'recommend_slot_effect_強韌髮絲', 'recommend_slot_effect_豐盈', 'recommend_slot_effect_抗痘', 'recommend_slot_effect_改善粉刺', 'recommend_slot_effect_不致痘', 'recommend_slot_effect_不致粉刺', 'recommend_slot_effect_抗空汙', 'recommend_slot_effect_改善水腫', 'recommend_slot_effect_改善紋路', 'recommend_slot_effect_光滑', 'recommend_slot_effect_護色', 'recommend_slot_effect_快乾', 'recommend_slot_effect_預防落髮', 'recommend_slot_effect_飽和色', 'recommend_slot_effect_漆亮感', 'recommend_slot_effect_果凍色', 'recommend_slot_effect_抗屑'
]

PRODUCT_EFFECT = {
    "氣墊粉餅": [
        "美白",
        "透亮",
        "長效持妝",
        "防曬",
        "遮瑕",
        "保濕",
        "修正膚色",
        "滋潤",
        "抗老",
        "服貼",
        "好推勻",
        "控油",
        "防水",
        "清爽",
        "潤色",
        "修飾毛孔",
        "均勻膚色",
        "薄透",
        "光澤",
        "好上色",
        "修容",
        "霧面",
        "打亮",
        "細緻",
        "防油",
        "珠光"
    ],
    "防曬隔離": [
        "保濕",
        "滋潤",
        "防曬",
        "清爽",
        "不黏膩",
        "香氛",
        "好吸收",
        "透亮",
        "控油",
        "均勻膚色",
        "修護",
        "舒緩",
        "提升光澤",
        "抗氧化",
        "潤色",
        "美白",
        "平滑膚觸",
        "溫和低刺激",
        "抗空汙",
        "細緻毛孔",
        "抗痘",
        "抗老"
    ],
    "唇部保養": [
        "保濕",
        "滋潤",
        "改善細紋",
        "防曬",
        "修護",
        "提升光澤",
        "潤色",
        "不黏膩",
        "好吸收",
        "清爽",
        "均勻膚色",
        "平滑膚觸",
        "舒緩",
        "溫和低刺激",
        "抗老",
        "透亮",
        "去角質",
        "卸妝",
        "香氛",
        "抗氧化",
        "緊實",
        "抗皺",
        "改善水腫",
        "拉提",
        "抗空汙"
    ],
    "美胸保養": [
        "保濕",
        "滋潤",
        "緊實",
        "舒緩",
        "香氛",
        "平滑膚觸"
    ],
    "精華油": [
        "保濕",
        "滋潤",
        "抗老",
        "緊實",
        "拉提",
        "抗皺",
        "修護",
        "改善細紋",
        "美白",
        "透亮",
        "均勻膚色",
        "淡斑",
        "提升光澤",
        "平滑膚觸",
        "舒緩",
        "抗氧化",
        "香氛",
        "收斂毛孔",
        "控油",
        "抗痘",
        "改善粉刺",
        "細緻毛孔",
        "去角質",
        "好吸收",
        "清爽",
        "不黏膩"
    ],
    "男仕臉部保養": [
        "保濕",
        "滋潤",
        "控油",
        "舒緩",
        "清爽",
        "好吸收",
        "不黏膩",
        "提升光澤",
        "抗老",
        "緊實",
        "改善細紋",
        "拉提",
        "抗皺",
        "修護"
    ],
    "洗髮品": [
        "保濕",
        "清潔",
        "滋潤",
        "柔順",
        "香氛",
        "預防落髮",
        "亮澤",
        "光滑",
        "強韌髮絲",
        "修護",
        "豐盈",
        "護色",
        "抗屑",
        "控油"
    ],
    "化妝水": [
        "保濕",
        "滋潤",
        "修護",
        "美白",
        "透亮",
        "提升光澤",
        "平滑膚觸",
        "抗氧化",
        "舒緩",
        "清爽",
        "緊實",
        "改善細紋",
        "控油",
        "細緻毛孔",
        "均勻膚色",
        "不黏膩",
        "好吸收",
        "淡斑",
        "抗痘",
        "改善粉刺",
        "拉提",
        "去角質",
        "深層清潔",
        "溫和低刺激",
        "清潔",
        "香氛",
        "收斂毛孔",
        "卸妝",
        "抗皺",
        "抗老",
        "抗空汙"
    ],
    "BB霜": [
        "潤色",
        "修飾毛孔",
        "遮瑕",
        "保濕",
        "透亮",
        "長效持妝",
        "服貼",
        "美白",
        "修正膚色",
        "光澤",
        "均勻膚色",
        "防曬",
        "薄透",
        "清爽",
        "不致痘",
        "抗老",
        "控油",
        "滋潤",
        "好推勻",
        "防水",
        "好上色",
        "打亮",
        "亮片",
        "細緻"
    ],
    "乳液": [
        "保濕",
        "滋潤",
        "抗老",
        "緊實",
        "拉提",
        "修護",
        "細緻毛孔",
        "抗氧化",
        "舒緩",
        "香氛",
        "提升光澤",
        "平滑膚觸",
        "好吸收",
        "美白",
        "不黏膩",
        "透亮",
        "均勻膚色",
        "淡斑",
        "清爽",
        "收斂毛孔",
        "控油",
        "抗痘",
        "改善粉刺",
        "溫和低刺激",
        "防曬",
        "改善細紋",
        "抗皺",
        "潤色",
        "抗空汙",
        "去角質"
    ],
    "遮瑕": [
        "服貼",
        "防曬",
        "遮瑕",
        "保濕",
        "修飾毛孔",
        "長效持妝",
        "防水",
        "防油",
        "抗老",
        "修正膚色",
        "光澤",
        "修容",
        "滋潤",
        "薄透",
        "打亮",
        "好推勻",
        "透亮",
        "清爽",
        "控油",
        "均勻膚色",
        "細緻",
        "不致痘",
        "潤色",
        "抗暈染",
        "好上色",
        "美白"
    ],
    "精油": [],
    "CC霜": [
        "服貼",
        "薄透",
        "好推勻",
        "潤色",
        "修正膚色",
        "修飾毛孔",
        "均勻膚色",
        "控油",
        "長效持妝",
        "清爽",
        "保濕",
        "光澤",
        "防曬",
        "遮瑕",
        "滋潤",
        "透亮",
        "不致痘",
        "打亮",
        "美白",
        "防水"
    ],
    "睫毛膏": [
        "抗暈染",
        "纖長",
        "根根分明",
        "防水",
        "捲翹",
        "濃密",
        "防油",
        "溫水可卸",
        "保濕",
        "長效持妝",
        "細緻",
        "色彩飽和",
        "滋潤",
        "顯色",
        "好上色"
    ],
    "洗顏產品": [
        "清潔",
        "保濕",
        "滋潤",
        "卸妝",
        "去角質",
        "平滑膚觸",
        "深層清潔",
        "美白",
        "緊實",
        "抗痘",
        "改善粉刺",
        "細緻毛孔",
        "收斂毛孔",
        "透亮",
        "控油",
        "修護",
        "舒緩",
        "提升光澤",
        "清爽",
        "溫和低刺激",
        "不黏膩",
        "香氛",
        "均勻膚色",
        "抗老",
        "抗氧化",
        "抗皺",
        "抗空汙",
        "改善細紋",
        "好吸收"
    ],
    "爽身制汗品": [
        "溫和低刺激",
        "香氛",
        "清爽",
        "舒緩"
    ],
    "精華液": [
        "保濕",
        "滋潤",
        "抗老",
        "緊實",
        "拉提",
        "抗皺",
        "修護",
        "改善細紋",
        "透亮",
        "清爽",
        "美白",
        "均勻膚色",
        "淡斑",
        "不黏膩",
        "好吸收",
        "收斂毛孔",
        "控油",
        "抗痘",
        "溫和低刺激",
        "細緻毛孔",
        "抗空汙",
        "抗氧化",
        "平滑膚觸",
        "提升光澤",
        "改善粉刺",
        "舒緩",
        "去角質",
        "防曬",
        "改善水腫",
        "深層清潔",
        "香氛",
        "清潔"
    ],
    "蜜粉": [
        "保濕",
        "控油",
        "長效持妝",
        "珠光",
        "修正膚色",
        "修飾毛孔",
        "透亮",
        "均勻膚色",
        "防曬",
        "薄透",
        "光澤",
        "打亮",
        "不致痘",
        "服貼",
        "遮瑕",
        "細緻",
        "清爽",
        "霧面",
        "修容",
        "美白",
        "抗老",
        "好推勻",
        "色彩飽和",
        "潤色",
        "好上色",
        "不致粉刺",
        "亮片"
    ],
    "擴香": [],
    "髮妝造型": [
        "保濕",
        "亮澤",
        "香氛",
        "豐盈",
        "修護",
        "滋潤",
        "柔順",
        "光滑",
        "強韌髮絲"
    ],
    "粉餅": [
        "保濕",
        "控油",
        "長效持妝",
        "滋潤",
        "修飾毛孔",
        "透亮",
        "美白",
        "服貼",
        "均勻膚色",
        "防曬",
        "遮瑕",
        "潤色",
        "修正膚色",
        "清爽",
        "薄透",
        "光澤",
        "珠光",
        "不致粉刺",
        "防水",
        "霧面",
        "細緻",
        "修容",
        "打亮",
        "好推勻",
        "不致痘",
        "防油",
        "抗老",
        "好上色"
    ],
    "唇膏": [
        "保濕",
        "顯色",
        "長效持妝",
        "好上色",
        "好推勻",
        "色彩飽和",
        "滋潤",
        "服貼",
        "珠光",
        "光澤",
        "潤色",
        "防曬",
        "細緻",
        "透亮",
        "抗暈染",
        "霧面",
        "均勻膚色",
        "清爽",
        "防水",
        "薄透",
        "遮瑕",
        "修正膚色",
        "打亮"
    ],
    "染髮品": [],
    "身體清潔": [
        "深層清潔",
        "保濕",
        "滋潤",
        "平滑膚觸",
        "香氛",
        "舒緩",
        "清爽",
        "溫和低刺激",
        "提升光澤",
        "美白",
        "透亮",
        "去角質",
        "緊實",
        "改善水腫"
    ],
    "身體保養": [
        "保濕",
        "滋潤",
        "舒緩",
        "香氛",
        "清爽",
        "溫和低刺激",
        "平滑膚觸",
        "提升光澤",
        "透亮",
        "改善紋路",
        "均勻膚色",
        "去角質",
        "美白",
        "緊實"
    ],
    "保濕噴霧": [
        "保濕",
        "滋潤",
        "舒緩",
        "抗痘",
        "改善粉刺",
        "溫和低刺激",
        "好吸收",
        "香氛",
        "清爽",
        "收斂毛孔",
        "控油",
        "細緻毛孔",
        "透亮",
        "不黏膩",
        "提升光澤",
        "修護"
    ],
    "前導保養": [
        "保濕",
        "滋潤",
        "提升光澤",
        "好吸收",
        "修護",
        "細緻毛孔",
        "透亮",
        "舒緩",
        "不黏膩",
        "控油",
        "抗痘",
        "改善粉刺",
        "平滑膚觸",
        "溫和低刺激",
        "抗老",
        "抗氧化",
        "緊實",
        "美白"
    ],
    "香氛噴霧": [],
    "手部保養": [
        "保濕",
        "滋潤",
        "舒緩",
        "香氛",
        "緊實",
        "平滑膚觸",
        "改善紋路",
        "清爽",
        "去角質",
        "提升光澤",
        "溫和低刺激",
        "透亮",
        "美白"
    ],
    "手部清潔": [
        "去角質",
        "保濕",
        "滋潤",
        "香氛",
        "清爽",
        "深層清潔",
        "溫和低刺激"
    ],
    "眼部保養": [
        "保濕",
        "滋潤",
        "抗老",
        "緊實",
        "修護",
        "改善細紋",
        "透亮",
        "提升光澤",
        "美白",
        "抗皺",
        "溫和低刺激",
        "舒緩",
        "清爽",
        "不黏膩",
        "好吸收",
        "平滑膚觸",
        "拉提",
        "抗氧化",
        "香氛",
        "改善水腫",
        "均勻膚色",
        "淡斑",
        "清潔",
        "細緻毛孔"
    ],
    "妝前打底": [
        "潤色",
        "修正膚色",
        "透亮",
        "保濕",
        "光澤",
        "長效持妝",
        "防曬",
        "薄透",
        "修飾毛孔",
        "服貼",
        "控油",
        "珠光",
        "均勻膚色",
        "遮瑕",
        "好推勻",
        "打亮",
        "清爽",
        "不致痘",
        "防水",
        "好上色",
        "抗暈染",
        "顯色",
        "防油",
        "色彩飽和",
        "霧面",
        "不致粉刺",
        "滋潤",
        "細緻",
        "修容",
        "美白"
    ],
    "臉部去角質": [
        "清潔",
        "去角質",
        "透亮",
        "保濕",
        "溫和低刺激",
        "深層清潔",
        "收斂毛孔",
        "控油",
        "均勻膚色",
        "滋潤",
        "細緻毛孔",
        "平滑膚觸",
        "緊實",
        "修護",
        "改善粉刺",
        "提升光澤",
        "抗空汙",
        "舒緩",
        "抗痘",
        "美白",
        "抗皺",
        "改善細紋",
        "清爽",
        "香氛",
        "抗氧化"
    ],
    "腿足保養": [
        "保濕",
        "滋潤",
        "改善紋路",
        "舒緩",
        "平滑膚觸",
        "香氛",
        "去角質"
    ],
    "粉條": [
        "光澤",
        "服貼",
        "遮瑕",
        "打亮",
        "保濕",
        "修正膚色",
        "修飾毛孔",
        "均勻膚色",
        "長效持妝",
        "好上色",
        "好推勻",
        "清爽",
        "潤色",
        "透亮"
    ],
    "凝膠凝凍": [
        "保濕",
        "修護",
        "透亮",
        "提升光澤",
        "舒緩",
        "清爽",
        "滋潤",
        "不黏膩",
        "美白",
        "緊實",
        "抗皺",
        "改善細紋",
        "好吸收",
        "改善粉刺",
        "淡斑",
        "收斂毛孔",
        "控油",
        "抗痘",
        "清潔",
        "防曬",
        "深層清潔",
        "細緻毛孔",
        "溫和低刺激",
        "香氛",
        "去角質",
        "平滑膚觸",
        "均勻膚色",
        "抗老",
        "拉提",
        "抗氧化",
        "抗空汙"
    ],
    "美甲工具": [
        "光澤",
        "飽和色"
    ],
    "頭皮養護": [
        "修護",
        "滋潤",
        "光滑",
        "柔順",
        "亮澤",
        "預防落髮",
        "強韌髮絲",
        "保濕",
        "香氛"
    ],
    "卸妝產品": [
        "卸妝",
        "保濕",
        "清爽",
        "清潔",
        "細緻毛孔",
        "控油",
        "舒緩",
        "溫和低刺激",
        "不黏膩",
        "深層清潔",
        "透亮",
        "平滑膚觸",
        "香氛",
        "滋潤",
        "去角質",
        "收斂毛孔",
        "抗痘",
        "改善細紋",
        "修護",
        "提升光澤",
        "抗老"
    ],
    "體香制汗": [],
    "指甲油": [
        "光澤",
        "飽和色",
        "快乾",
        "霧面",
        "亮片",
        "漆亮感",
        "果凍色",
        "珠光"
    ],
    "身體防曬": [
        "保濕",
        "香氛",
        "清爽",
        "均勻膚色",
        "溫和低刺激",
        "平滑膚觸",
        "滋潤",
        "提升光澤",
        "緊實"
    ],
    "唇筆": [
        "好推勻",
        "光澤",
        "顯色",
        "好上色",
        "修容",
        "滋潤",
        "保濕",
        "潤色",
        "透亮",
        "抗暈染",
        "長效持妝",
        "色彩飽和",
        "霧面",
        "細緻"
    ],
    "美甲保養": [
        "光澤"
    ],
    "私密處護理": [
        "深層清潔",
        "舒緩",
        "清爽",
        "滋潤",
        "保濕"
    ],
    "護髮品": [
        "保濕",
        "柔順",
        "亮澤",
        "修護",
        "香氛",
        "光滑",
        "強韌髮絲",
        "滋潤",
        "豐盈",
        "護色",
        "預防落髮"
    ],
    "彩妝工具": [],
    "唇彩唇蜜": [
        "保濕",
        "長效持妝",
        "顯色",
        "好上色",
        "好推勻",
        "色彩飽和",
        "霧面",
        "服貼",
        "珠光",
        "修容",
        "滋潤",
        "潤色",
        "光澤",
        "細緻",
        "透亮",
        "打亮",
        "抗暈染",
        "修正膚色",
        "修飾毛孔",
        "遮瑕",
        "薄透",
        "均勻膚色",
        "亮片",
        "濃密"
    ],
    "粉底液": [
        "遮瑕",
        "薄透",
        "滋潤",
        "保濕",
        "潤色",
        "修正膚色",
        "修飾毛孔",
        "透亮",
        "均勻膚色",
        "服貼",
        "好上色",
        "控油",
        "清爽",
        "防曬",
        "長效持妝",
        "好推勻",
        "光澤",
        "打亮",
        "霧面",
        "細緻",
        "抗老",
        "顯色",
        "防水"
    ],
    "保養工具": [
        "抗痘"
    ],
    "男仕刮鬍護理": [
        "保濕",
        "滋潤"
    ],
    "女性香氛": [],
    "保養面膜": [
        "保濕",
        "滋潤",
        "修護",
        "緊實",
        "透亮",
        "平滑膚觸",
        "溫和低刺激",
        "提升光澤",
        "美白",
        "收斂毛孔",
        "控油",
        "改善細紋",
        "抗老",
        "細緻毛孔",
        "均勻膚色",
        "拉提",
        "舒緩",
        "深層清潔",
        "抗皺",
        "去角質",
        "清爽",
        "淡斑",
        "改善粉刺",
        "好吸收",
        "抗痘",
        "清潔",
        "抗氧化",
        "不黏膩",
        "香氛",
        "抗空汙",
        "改善水腫"
    ],
    "腮紅修容": [
        "顯色",
        "好上色",
        "好推勻",
        "細緻",
        "修容",
        "服貼",
        "珠光",
        "滋潤",
        "保濕",
        "光澤",
        "打亮",
        "色彩飽和",
        "長效持妝",
        "修正膚色",
        "遮瑕",
        "薄透",
        "控油",
        "透亮",
        "潤色",
        "修飾毛孔",
        "不致痘",
        "霧面",
        "清爽",
        "均勻膚色",
        "防水",
        "防油",
        "亮片",
        "抗暈染"
    ],
    "乳霜": [
        "保濕",
        "滋潤",
        "抗老",
        "緊實",
        "修護",
        "舒緩",
        "改善細紋",
        "透亮",
        "均勻膚色",
        "提升光澤",
        "平滑膚觸",
        "防曬",
        "抗皺",
        "好吸收",
        "拉提",
        "美白",
        "抗痘",
        "改善粉刺",
        "不黏膩",
        "清爽",
        "收斂毛孔",
        "細緻毛孔",
        "抗氧化",
        "淡斑",
        "香氛",
        "溫和低刺激",
        "潤色",
        "抗空汙",
        "控油",
        "改善水腫",
        "清潔"
    ],
    "身體去角質": [
        "去角質",
        "保濕",
        "滋潤",
        "均勻膚色",
        "緊實",
        "美白",
        "深層清潔",
        "香氛",
        "提升光澤",
        "改善水腫",
        "平滑膚觸"
    ],
    "眉彩": [
        "長效持妝",
        "薄透",
        "好上色",
        "色彩飽和",
        "防水",
        "好推勻",
        "細緻",
        "顯色",
        "防油",
        "抗暈染",
        "服貼",
        "打亮",
        "光澤",
        "保濕",
        "珠光",
        "修容",
        "滋潤",
        "溫水可卸",
        "根根分明",
        "濃密",
        "霧面",
        "清爽"
    ],
    "眼線": [
        "顯色",
        "好上色",
        "好推勻",
        "防水",
        "抗暈染",
        "長效持妝",
        "防油",
        "色彩飽和",
        "細緻",
        "服貼",
        "珠光",
        "亮片",
        "溫水可卸",
        "打亮",
        "保濕",
        "光澤",
        "滋潤"
    ],
    "潤髮品": [
        "保濕",
        "柔順",
        "香氛",
        "修護",
        "控油",
        "抗屑",
        "豐盈",
        "護色",
        "滋潤",
        "亮澤",
        "強韌髮絲",
        "光滑"
    ],
    "眼影": [
        "珠光",
        "顯色",
        "好推勻",
        "色彩飽和",
        "霧面",
        "好上色",
        "服貼",
        "光澤",
        "長效持妝",
        "薄透",
        "防水",
        "抗暈染",
        "打亮",
        "防油",
        "修容",
        "均勻膚色",
        "遮瑕",
        "滋潤",
        "亮片",
        "保濕",
        "透亮",
        "細緻",
        "潤色",
        "控油"
    ],
    "清潔面膜": [
        "清潔",
        "深層清潔",
        "收斂毛孔",
        "控油",
        "抗痘",
        "改善粉刺",
        "滋潤",
        "細緻毛孔",
        "提升光澤",
        "緊實",
        "透亮",
        "舒緩",
        "保濕",
        "平滑膚觸",
        "溫和低刺激",
        "去角質",
        "修護",
        "抗氧化",
        "抗空汙",
        "美白",
        "均勻膚色",
        "清爽",
        "拉提",
        "香氛",
        "抗老"
    ],
    "營養輔助食品": [
        "緊實",
        "保濕",
        "滋潤"
    ],
    "眼唇卸妝": [
        "卸妝",
        "保濕",
        "滋潤",
        "溫和低刺激",
        "緊實",
        "修護",
        "舒緩",
        "清爽",
        "不黏膩",
        "清潔"
    ],
    "香氛蠟燭": [],
    "勻體緊實產品": [
        "保濕",
        "滋潤",
        "舒緩",
        "平滑膚觸",
        "緊實",
        "改善紋路",
        "香氛",
        "提升光澤"
    ],
    "粉霜": [
        "保濕",
        "修飾毛孔",
        "遮瑕",
        "修正膚色",
        "光澤",
        "透亮",
        "服貼",
        "修容",
        "清爽",
        "均勻膚色",
        "好推勻",
        "控油",
        "美白",
        "滋潤",
        "長效持妝",
        "防曬",
        "抗老",
        "薄透",
        "潤色",
        "霧面"
    ]
}

PRODUCT_BRAND = {
    "精華液": [
        "MISSHA",
        "Hada-Labo 肌研",
        "ettusais 艾杜紗",
        "FRUSIRNANA 美膚娜娜",
        "MAYSKIN 優若美",
        "FASHION K-BEAUTY",
        "NIVEA 妮維雅",
        "CHAPEX 喬沛詩",
        "Dr. Jart+",
        "Avene 雅漾",
        "ALOEDERMA 璦露德瑪",
        "TSZJITSUEI 瓷肌萃",
        "YOUBEST 優倍多",
        "Pure Beauty",
        "innisfree",
        "PERLABELLA 義貝拉",
        "divinia 蒂芬妮亞",
        "banila co.",
        "80",
        "PALMER'S 帕瑪氏",
        "Bio oil 百洛",
        "GARNIER 卡尼爾",
        "NEOGENCE 霓淨思",
        "CHRONO AFFECTION 時間寵愛",
        "L'OREAL PARIS 巴黎萊雅",
        "BIONIKE",
        "CHLITINA 克麗緹娜",
        "UNT",
        "Curel 珂潤",
        "SOFINA 蘇菲娜",
        "NEUTROGENA 露得清",
        "JINGCHENG 京城之霜",
        "DHC",
        "WHITE FORMULA 自白肌",
        "CNP LABORATORY",
        "St.Clare 聖克萊爾",
        "Target PRO by Watsons",
        "webner 葦柏納",
        "SKIN Advanced",
        "am+pm skincare",
        "AQUA LABEL 水之印",
        "Dr.Hsieh 達特醫",
        "OLAY 歐蕾",
        "Dr.Satin",
        "ZA",
        "AVALON",
        "Bio-essence 碧歐斯",
        "LA ROCHE-POSAY 理膚寶水",
        "EQUILIBRA 義貝拉",
        "Derma Formula 美肌醫生",
        "dermalogica 德卡",
        "法國歐德瑪",
        "Skinfood",
        "BEAUTIA 倍立雅",
        "NARUKO",
        "Reme+G 潤美肌",
        "DR.WU 達爾膚",
        "FOR BELOVED ONE 寵愛之名",
        "KISS ME 奇士美",
        "Collagen",
        "SwissVita 瑞士薇佳",
        "Jericho",
        "VICHY 薇姿",
        "Sulwhasoo 雪花秀",
        "BURT'S BEES 小蜜蜂爺爺",
        "Valmont 法兒曼",
        "AYURA 東洋美學",
        "NEO-TEC 妮傲絲翠"
    ],
    "粉霜": [
        "media 媚點",
        "CANMAKE",
        "I’M MEME",
        "DR.WU 達爾膚",
        "KAI DELUXE 型色大師"
    ],
    "手部保養": [
        "babaria 西班牙babaria",
        "Kamill",
        "Institut Karite Paris 巴黎乳油木",
        "NEUTROGENA 露得清",
        "Erborian 艾博妍",
        "eos 伊歐詩",
        "Dr.Satin",
        "TONYMOLY",
        "Marykay 玫琳凱",
        "L'EGERE 蘭吉兒",
        "WATSONSSKIN 屈臣氏"
    ],
    "保濕噴霧": [
        "廣源良",
        "FRUSIRNANA 美膚娜娜",
        "Avene 雅漾",
        "innisfree",
        "專科",
        "BELLABEAUTY",
        "NEOGENCE 霓淨思",
        "Dr.Satin",
        "Bio-essence 碧歐斯",
        "LA ROCHE-POSAY 理膚寶水",
        "too cool for school",
        "OGUMA 水美媒",
        "VICHY 薇姿"
    ],
    "BB霜": [
        "MISSHA",
        "media 媚點",
        "ettusais 艾杜紗",
        "Dr. Jart+",
        "專科",
        "KATE 凱婷",
        "L'OREAL PARIS 巴黎萊雅",
        "Curel 珂潤",
        "SOFINA 蘇菲娜",
        "Freshel 膚蕊",
        "ZA",
        "Bio-essence 碧歐斯",
        "CEZANNE",
        "Rebecca Bonbon",
        "NACOLA",
        "MAYBELLINE 媚比琳",
        "VICHY 薇姿",
        "CLIO 珂莉奧",
        "BURT'S BEES 小蜜蜂爺爺",
        "MENTHOLATUM 曼秀雷敦",
        "FASIO 菲希歐"
    ],
    "卸妝產品": [
        "Hada-Labo 肌研",
        "eSpoir",
        "heme",
        "ettusais 艾杜紗",
        "NIVEA 妮維雅",
        "VOO DOO",
        "DERMEDIC",
        "Dr.Morita 森田藥粧",
        "Natracare",
        "Avene 雅漾",
        "MAJOLICA MAJORCA 戀愛魔鏡",
        "CETAPHIL 舒特膚",
        "KOSE COSMEPORT 蔻絲魅寶",
        "專科",
        "divinia 蒂芬妮亞",
        "banila co.",
        "PALMER'S 帕瑪氏",
        "GARNIER 卡尼爾",
        "NEOGENCE 霓淨思",
        "A-DERMA 艾芙美",
        "CHRONO AFFECTION 時間寵愛",
        "FROMNATURE",
        "L'OREAL PARIS 巴黎萊雅",
        "Dove 多芬",
        "BIONIKE",
        "UNT",
        "SKINBIOTEC 肌研生醫",
        "Curel 珂潤",
        "SOFINA 蘇菲娜",
        "NEUTROGENA 露得清",
        "MYSCHEMING 我的心機",
        "JINGCHENG 京城之霜",
        "DHC",
        "POND'S 旁氏",
        "Bioderma 法國貝德瑪",
        "CNP LABORATORY",
        "webner 葦柏納",
        "A'PIEU",
        "Freshel 膚蕊",
        "AQUA LABEL 水之印",
        "FITIT&WHITIA",
        "Dr.Satin",
        "ZA",
        "Bio-essence 碧歐斯",
        "CANMAKE",
        "LA ROCHE-POSAY 理膚寶水",
        "EQUILIBRA 義貝拉",
        "法國歐德瑪",
        "奢華寶貝",
        "too cool for school",
        "AZZEEN 芝妍",
        "SKINLIFE 滋卿愛",
        "MAYBELLINE 媚比琳",
        "ROSYROSA",
        "DR.WU 達爾膚",
        "FOR BELOVED ONE 寵愛之名",
        "KISS ME 奇士美",
        "Jericho",
        "BOURJOIS 妙巴黎",
        "Softymo 絲芙蒂",
        "VICHY 薇姿",
        "AVIVA",
        "Bifesta",
        "BeautyMaker",
        "WATSONSSKIN 屈臣氏",
        "HARMONY",
        "nooni",
        "1028",
        "Biore 蜜妮"
    ],
    "精華油": [
        "Dermaction",
        "PALMER'S 帕瑪氏",
        "CHRONO AFFECTION 時間寵愛",
        "L'OREAL PARIS 巴黎萊雅",
        "EVOLU 艾芙洛",
        "OLAY 歐蕾",
        "Bio-essence 碧歐斯",
        "Sulwhasoo 雪花秀"
    ],
    "勻體緊實產品": [
        "dermalogica 德卡"
    ],
    "潤髮品": [
        "TSUBAKI 思波綺",
        "AVALON",
        "ALTERNA",
        "KLORANE 蔻蘿蘭",
        "FASIO 菲希歐"
    ],
    "妝前打底": [
        "MISSHA",
        "media 媚點",
        "MAJOLICA MAJORCA 戀愛魔鏡",
        "KOSE COSMEPORT 蔻絲魅寶",
        "KATE 凱婷",
        "L'OREAL PARIS 巴黎萊雅",
        "UNT",
        "SOFINA 蘇菲娜",
        "Hope Girl",
        "INTEGRATE 絕色魅癮",
        "A'PIEU",
        "AQUA LABEL 水之印",
        "CANMAKE",
        "Absolute New York 絕色紐約",
        "dermalogica 德卡",
        "I’M MEME",
        "too cool for school",
        "CEZANNE",
        "REVLON 露華濃",
        "MAYBELLINE 媚比琳",
        "FOR BELOVED ONE 寵愛之名",
        "KISS ME 奇士美",
        "VDL",
        "N.A.F",
        "CLIO 珂莉奧",
        "Sulwhasoo 雪花秀",
        "1028",
        "Biore 蜜妮",
        "PONY EFFECT"
    ],
    "防曬隔離": [
        "Hada-Labo 肌研",
        "heme",
        "media 媚點",
        "ettusais 艾杜紗",
        "FRUSIRNANA 美膚娜娜",
        "NIVEA 妮維雅",
        "CORSICA 科皙佳",
        "Dr. Jart+",
        "Avene 雅漾",
        "CETAPHIL 舒特膚",
        "KOSE COSMEPORT 蔻絲魅寶",
        "YOUBEST 優倍多",
        "專科",
        "PALMER'S 帕瑪氏",
        "GARNIER 卡尼爾",
        "NEOGENCE 霓淨思",
        "CHRONO AFFECTION 時間寵愛",
        "L'OREAL PARIS 巴黎萊雅",
        "Curel 珂潤",
        "SOFINA 蘇菲娜",
        "NEUTROGENA 露得清",
        "Cellina 雪芙蘭",
        "DHC",
        "Bioderma 法國貝德瑪",
        "WHITE FORMULA 自白肌",
        "am+pm skincare",
        "AQUA LABEL 水之印",
        "OLAY 歐蕾",
        "Dr.Satin",
        "ZA",
        "Bio-essence 碧歐斯",
        "LA ROCHE-POSAY 理膚寶水",
        "dermalogica 德卡",
        "YUSKIN 悠斯晶",
        "DR.WU 達爾膚",
        "Collagen",
        "VICHY 薇姿",
        "MENTHOLATUM 曼秀雷敦",
        "1028",
        "FASIO 菲希歐",
        "LOVECODE",
        "Biore 蜜妮",
        "Vaseline 凡士林"
    ],
    "男仕臉部保養": [
        "NIVEA 妮維雅"
    ],
    "凝膠凝凍": [
        "MISSHA",
        "Hada-Labo 肌研",
        "廣源良",
        "ettusais 艾杜紗",
        "西班牙Babaria",
        "3M",
        "FRUSIRNANA 美膚娜娜",
        "Dr.Morita 森田藥粧",
        "Avene 雅漾",
        "KOSE COSMEPORT 蔻絲魅寶",
        "ALOEDERMA 璦露德瑪",
        "La Formule 法國植萃合度",
        "YOUBEST 優倍多",
        "divinia 蒂芬妮亞",
        "BELLABEAUTY",
        "banila co.",
        "GARNIER 卡尼爾",
        "NEOGENCE 霓淨思",
        "L'OREAL PARIS 巴黎萊雅",
        "ONCE",
        "CHLITINA 克麗緹娜",
        "Curel 珂潤",
        "NEUTROGENA 露得清",
        "WHITE FORMULA 自白肌",
        "CNP LABORATORY",
        "St.Clare 聖克萊爾",
        "am+pm skincare",
        "Freshel 膚蕊",
        "AQUA LABEL 水之印",
        "Dr.Hsieh 達特醫",
        "OLAY 歐蕾",
        "ZA",
        "Bio-essence 碧歐斯",
        "LA ROCHE-POSAY 理膚寶水",
        "dermalogica 德卡",
        "NARUKO",
        "Collagen",
        "Jericho",
        "SYRIO",
        "VICHY 薇姿",
        "BONANZA 寶藝",
        "BeautyMaker",
        "Vaseline 凡士林"
    ],
    "洗髮品": [
        "Institut Karite Paris 巴黎乳油木",
        "TSUBAKI 思波綺",
        "L'OREAL PARIS 巴黎萊雅",
        "Dove 多芬",
        "Rene Furterer 荷那法蕊",
        "EVOLU 艾芙洛",
        "DHC",
        "AVALON",
        "KLORANE 蔻蘿蘭",
        "RYO 呂",
        "FASIO 菲希歐"
    ],
    "睫毛膏": [
        "MISSHA",
        "heme",
        "media 媚點",
        "MAJOLICA MAJORCA 戀愛魔鏡",
        "MOTE",
        "KATE 凱婷",
        "dejavu",
        "L'OREAL PARIS 巴黎萊雅",
        "UNT",
        "INTEGRATE 絕色魅癮",
        "A'PIEU",
        "CHATEAU LABIOTTE",
        "ZA",
        "CANMAKE",
        "Absolute New York 絕色紐約",
        "奢華寶貝",
        "LA MER 海洋拉娜",
        "NACOLA",
        "REVLON 露華濃",
        "MAYBELLINE 媚比琳",
        "KISS ME 奇士美",
        "BOURJOIS 妙巴黎",
        "N.A.F",
        "Mistine",
        "1028",
        "FASIO 菲希歐",
        "Biore 蜜妮"
    ],
    "眼線": [
        "eSpoir",
        "heme",
        "media 媚點",
        "ettusais 艾杜紗",
        "MAJOLICA MAJORCA 戀愛魔鏡",
        "Anime Cosme",
        "KATE 凱婷",
        "AZPLAZA",
        "dejavu",
        "L'OREAL PARIS 巴黎萊雅",
        "UNT",
        "AZ-LB",
        "DHC",
        "INTEGRATE 絕色魅癮",
        "ZA",
        "CANMAKE",
        "BBIA",
        "Absolute New York 絕色紐約",
        "Reinachu 日本蕾娜啾",
        "奢華寶貝",
        "too cool for school",
        "CEZANNE",
        "NACOLA",
        "K-PALETTE",
        "REVLON 露華濃",
        "MAYBELLINE 媚比琳",
        "KISS ME 奇士美",
        "VDL",
        "BOURJOIS 妙巴黎",
        "N.A.F",
        "Solone",
        "CLIO 珂莉奧",
        "Peripera",
        "Mistine",
        "1028",
        "FASIO 菲希歐"
    ],
    "護髮品": [
        "MOROCCANOIL",
        "Institut Karite Paris 巴黎乳油木",
        "Jurlique 茱莉蔻",
        "L'OREAL PARIS 巴黎萊雅",
        "Rene Furterer 荷那法蕊",
        "DHC",
        "AVALON",
        "ALTERNA",
        "FASIO 菲希歐"
    ],
    "髮妝造型": [
        "Jurlique 茱莉蔻",
        "Rene Furterer 荷那法蕊",
        "ReVive 麗膚再生",
        "FASIO 菲希歐"
    ],
    "化妝水": [
        "MISSHA",
        "Hada-Labo 肌研",
        "廣源良",
        "ettusais 艾杜紗",
        "Dr.Morita 森田藥粧",
        "Dr. Jart+",
        "Avene 雅漾",
        "KOSE COSMEPORT 蔻絲魅寶",
        "Pure Beauty",
        "innisfree",
        "專科",
        "THE FACE SHOP 菲詩小舖",
        "divinia 蒂芬妮亞",
        "BELLABEAUTY",
        "SRBEAUTY",
        "banila co.",
        "Country & Stream",
        "CAUDALIE",
        "PALMER'S 帕瑪氏",
        "Dr.Organic",
        "NEOGENCE 霓淨思",
        "AZPLAZA",
        "dejavu",
        "CHRONO AFFECTION 時間寵愛",
        "L'OREAL PARIS 巴黎萊雅",
        "BIONIKE",
        "ONCE",
        "CHLITINA 克麗緹娜",
        "Curel 珂潤",
        "SOFINA 蘇菲娜",
        "NEUTROGENA 露得清",
        "MYSCHEMING 我的心機",
        "Cellina 雪芙蘭",
        "DHC",
        "Bioderma 法國貝德瑪",
        "WHITE FORMULA 自白肌",
        "CNP LABORATORY",
        "DR.BRONNER’S 布朗博士",
        "St.Clare 聖克萊爾",
        "HIKARU 喜凱露",
        "SKIN Advanced",
        "am+pm skincare",
        "Freshel 膚蕊",
        "AQUA LABEL 水之印",
        "OLAY 歐蕾",
        "Dr.Satin",
        "ZA",
        "AVALON",
        "Bio-essence 碧歐斯",
        "LA ROCHE-POSAY 理膚寶水",
        "EQUILIBRA 義貝拉",
        "Derma Formula 美肌醫生",
        "evian 愛維養",
        "Skinfood",
        "too cool for school",
        "IOPE",
        "CEZANNE",
        "NARUKO",
        "AZZEEN 芝妍",
        "SKINLIFE 滋卿愛",
        "DR.WU 達爾膚",
        "FOR BELOVED ONE 寵愛之名",
        "KISS ME 奇士美",
        "Collagen",
        "SwissVita 瑞士薇佳",
        "OGUMA 水美媒",
        "L'EGERE 蘭吉兒",
        "Jericho",
        "VICHY 薇姿",
        "Bifesta",
        "MENTHOLATUM 曼秀雷敦",
        "Valmont 法兒曼",
        "Revlis",
        "LOVECODE",
        "Biore 蜜妮",
        "AYURA 東洋美學"
    ],
    "唇膏": [
        "MISSHA",
        "eSpoir",
        "heme",
        "media 媚點",
        "ettusais 艾杜紗",
        "MAJOLICA MAJORCA 戀愛魔鏡",
        "banila co.",
        "KATE 凱婷",
        "L'OREAL PARIS 巴黎萊雅",
        "UNT",
        "SOFINA 蘇菲娜",
        "DHC",
        "INTEGRATE 絕色魅癮",
        "3CE",
        "CHATEAU LABIOTTE",
        "ANIMECOSME",
        "PALTAC",
        "ZA",
        "CANMAKE",
        "MEMEBOX",
        "BBIA",
        "Absolute New York 絕色紐約",
        "Skinfood",
        "Pure Beauty",
        "奢華寶貝",
        "I’M MEME",
        "too cool for school",
        "IOPE",
        "CEZANNE",
        "NACOLA",
        "REVLON 露華濃",
        "MAYBELLINE 媚比琳",
        "VDL",
        "BOURJOIS 妙巴黎",
        "Solone",
        "CLIO 珂莉奧",
        "A'PIEU",
        "BURT'S BEES 小蜜蜂爺爺",
        "BeautyMaker",
        "Mistine",
        "1028",
        "FASIO 菲希歐"
    ],
    "爽身制汗品": [
        "Dove 多芬"
    ],
    "CC霜": [
        "heme",
        "ettusais 艾杜紗",
        "Pure Beauty",
        "THE FACE SHOP 菲詩小舖",
        "divinia 蒂芬妮亞",
        "banila co.",
        "UNT",
        "INTEGRATE 絕色魅癮",
        "Freshel 膚蕊",
        "Dr.Satin",
        "ZA",
        "奢華寶貝",
        "Beautymate 美肌之誌",
        "MAYBELLINE 媚比琳",
        "L'EGERE 蘭吉兒",
        "BOURJOIS 妙巴黎",
        "CLIO 珂莉奧",
        "BeautyMaker",
        "1028"
    ],
    "眼影": [
        "MISSHA",
        "eSpoir",
        "heme",
        "media 媚點",
        "MAJOLICA MAJORCA 戀愛魔鏡",
        "banila co.",
        "KATE 凱婷",
        "L'OREAL PARIS 巴黎萊雅",
        "SOFINA 蘇菲娜",
        "AZ-LB",
        "INTEGRATE 絕色魅癮",
        "CHATEAU LABIOTTE",
        "ZA",
        "CANMAKE",
        "BBIA",
        "Absolute New York 絕色紐約",
        "奢華寶貝",
        "I’M MEME",
        "LA MER 海洋拉娜",
        "CEZANNE",
        "NACOLA",
        "REVLON 露華濃",
        "MAYBELLINE 媚比琳",
        "KISS ME 奇士美",
        "BOURJOIS 妙巴黎",
        "Solone",
        "CLIO 珂莉奧",
        "Peripera",
        "A'PIEU",
        "KAI DELUXE 型色大師",
        "Mistine",
        "1028",
        "FASIO 菲希歐",
        "Biore 蜜妮",
        "PONY EFFECT"
    ],
    "私密處護理": [
        "SAUGELLA 賽吉兒"
    ],
    "腿足保養": [
        "babaria 西班牙babaria",
        "Institut Karite Paris 巴黎乳油木",
        "Face Queen 絕世愛美肌"
    ],
    "前導保養": [
        "SOFINA 蘇菲娜"
    ],
    "男仕刮鬍護理": [
        "Institut Karite Paris 巴黎乳油木"
    ],
    "粉餅": [
        "MISSHA",
        "heme",
        "media 媚點",
        "ettusais 艾杜紗",
        "MAJOLICA MAJORCA 戀愛魔鏡",
        "KATE 凱婷",
        "AZPLAZA",
        "L'OREAL PARIS 巴黎萊雅",
        "SOFINA 蘇菲娜",
        "INTEGRATE 絕色魅癮",
        "A'PIEU",
        "AQUA LABEL 水之印",
        "ZA",
        "CANMAKE",
        "Absolute New York 絕色紐約",
        "奢華寶貝",
        "CEZANNE",
        "NACOLA",
        "MAYBELLINE 媚比琳",
        "BOURJOIS 妙巴黎",
        "Sulwhasoo 雪花秀",
        "KAI DELUXE 型色大師",
        "BeautyMaker",
        "1028",
        "FASIO 菲希歐"
    ],
    "眼部保養": [
        "西班牙Babaria",
        "FASHION K-BEAUTY",
        "CHAPEX 喬沛詩",
        "Avene 雅漾",
        "MAJOLICA MAJORCA 戀愛魔鏡",
        "KOSE COSMEPORT 蔻絲魅寶",
        "MOTE",
        "YOUBEST 優倍多",
        "Pure Beauty",
        "innisfree",
        "專科",
        "Institut Karite Paris 巴黎乳油木",
        "SRBEAUTY",
        "banila co.",
        "Country & Stream",
        "PALMER'S 帕瑪氏",
        "GARNIER 卡尼爾",
        "NEOGENCE 霓淨思",
        "AZPLAZA",
        "L'OREAL PARIS 巴黎萊雅",
        "BIONIKE",
        "Curel 珂潤",
        "NEUTROGENA 露得清",
        "JINGCHENG 京城之霜",
        "DHC",
        "CNP LABORATORY",
        "Target PRO by Watsons",
        "SKIN Advanced",
        "OLAY 歐蕾",
        "Dr.Satin",
        "AVALON",
        "Bio-essence 碧歐斯",
        "LA ROCHE-POSAY 理膚寶水",
        "Jumelle 佐媚朵爾",
        "dermalogica 德卡",
        "法國歐德瑪",
        "CEZANNE",
        "NARUKO",
        "FOR BELOVED ONE 寵愛之名",
        "Collagen",
        "SwissVita 瑞士薇佳",
        "PURE SMILE",
        "Jericho",
        "VICHY 薇姿"
    ],
    "乳液": [
        "MISSHA",
        "Hada-Labo 肌研",
        "NIVEA 妮維雅",
        "CHAPEX 喬沛詩",
        "Avene 雅漾",
        "CETAPHIL 舒特膚",
        "KOSE COSMEPORT 蔻絲魅寶",
        "YOUBEST 優倍多",
        "Pure Beauty",
        "專科",
        "divinia 蒂芬妮亞",
        "banila co.",
        "PALMER'S 帕瑪氏",
        "NEOGENCE 霓淨思",
        "A-DERMA 艾芙美",
        "CHRONO AFFECTION 時間寵愛",
        "L'OREAL PARIS 巴黎萊雅",
        "CHLITINA 克麗緹娜",
        "UNT",
        "Curel 珂潤",
        "SOFINA 蘇菲娜",
        "NEUTROGENA 露得清",
        "Cellina 雪芙蘭",
        "JINGCHENG 京城之霜",
        "DHC",
        "Bioderma 法國貝德瑪",
        "WHITE FORMULA 自白肌",
        "St.Clare 聖克萊爾",
        "Target PRO by Watsons",
        "SKIN Advanced",
        "DCS",
        "Freshel 膚蕊",
        "AQUA LABEL 水之印",
        "OLAY 歐蕾",
        "FITIT&WHITIA",
        "Dr.Satin",
        "ZA",
        "Bio-essence 碧歐斯",
        "LA ROCHE-POSAY 理膚寶水",
        "Derma Formula 美肌醫生",
        "dermalogica 德卡",
        "法國歐德瑪",
        "Skinfood",
        "YUSKIN 悠斯晶",
        "NARUKO",
        "FOR BELOVED ONE 寵愛之名",
        "VICHY 薇姿",
        "Sulwhasoo 雪花秀",
        "A'PIEU",
        "alkmene"
    ],
    "唇部保養": [
        "ettusais 艾杜紗",
        "3M",
        "HIMALAYA 喜瑪拉雅",
        "NIVEA 妮維雅",
        "URIAGE 優麗雅",
        "MAJOLICA MAJORCA 戀愛魔鏡",
        "KOSE COSMEPORT 蔻絲魅寶",
        "CARMAX 小蜜媞",
        "Pure Paw Paw",
        "專科",
        "Institut Karite Paris 巴黎乳油木",
        "banila co.",
        "Country & Stream",
        "KATE 凱婷",
        "Curel 珂潤",
        "NEUTROGENA 露得清",
        "Cellina 雪芙蘭",
        "EVOLU 艾芙洛",
        "DHC",
        "INTEGRATE 絕色魅癮",
        "DR.BRONNER’S 布朗博士",
        "Target PRO by Watsons",
        "eos 伊歐詩",
        "KOSE 高絲",
        "CHATEAU LABIOTTE",
        "FITIT&WHITIA",
        "ZA",
        "CANMAKE",
        "LA ROCHE-POSAY 理膚寶水",
        "dermalogica 德卡",
        "too cool for school",
        "YUSKIN 悠斯晶",
        "MAYBELLINE 媚比琳",
        "VDL",
        "Arome by Watsons",
        "SYRIO",
        "VICHY 薇姿",
        "Sulwhasoo 雪花秀",
        "BURT'S BEES 小蜜蜂爺爺",
        "MENTHOLATUM 曼秀雷敦",
        "Vaseline 凡士林"
    ],
    "身體清潔": [
        "Kamill",
        "專科",
        "Institut Karite Paris 巴黎乳油木",
        "Dove 多芬",
        "UNT",
        "IBL 依必朗",
        "EVOLU 艾芙洛",
        "AVALON",
        "Johnson's 嬌生",
        "LA ROCHE-POSAY 理膚寶水",
        "PON PON 澎澎",
        "pHisoDerm 菲蘇德美",
        "Biore 蜜妮",
        "SAUGELLA 賽吉兒"
    ],
    "眼唇卸妝": [
        "MISSHA",
        "NIVEA 妮維雅",
        "APRIL SKIN",
        "divinia 蒂芬妮亞",
        "UNT",
        "NEUTROGENA 露得清",
        "FITIT&WHITIA",
        "BBIA",
        "MAYBELLINE 媚比琳",
        "KISS ME 奇士美",
        "BOURJOIS 妙巴黎",
        "VICHY 薇姿",
        "Bifesta",
        "BeautyMaker",
        "Mistine",
        "1028",
        "FASIO 菲希歐",
        "Biore 蜜妮"
    ],
    "唇筆": [
        "media 媚點",
        "ettusais 艾杜紗",
        "INTEGRATE 絕色魅癮",
        "ZA",
        "BBIA",
        "I’M MEME",
        "REVLON 露華濃",
        "BeautyMaker"
    ],
    "乳霜": [
        "MISSHA",
        "Hada-Labo 肌研",
        "廣源良",
        "LANCOME 蘭蔻",
        "babaria 西班牙babaria",
        "FRUSIRNANA 美膚娜娜",
        "AROA",
        "Dr. Jart+",
        "Avene 雅漾",
        "KOSE COSMEPORT 蔻絲魅寶",
        "TSZJITSUEI 瓷肌萃",
        "YOUBEST 優倍多",
        "Pure Beauty",
        "innisfree",
        "專科",
        "THE FACE SHOP 菲詩小舖",
        "divinia 蒂芬妮亞",
        "Institut Karite Paris 巴黎乳油木",
        "banila co.",
        "PALMER'S 帕瑪氏",
        "bonvivant",
        "GARNIER 卡尼爾",
        "NEOGENCE 霓淨思",
        "CHRONO AFFECTION 時間寵愛",
        "L'OREAL PARIS 巴黎萊雅",
        "BIONIKE",
        "Claire’s 格麗",
        "Curel 珂潤",
        "NEUTROGENA 露得清",
        "Hope Girl",
        "Hupanique 涵沛",
        "Bioderma 法國貝德瑪",
        "WHITE FORMULA 自白肌",
        "webner 葦柏納",
        "am+pm skincare",
        "Freshel 膚蕊",
        "AQUA LABEL 水之印",
        "OLAY 歐蕾",
        "Dr.Satin",
        "ZA",
        "AVALON",
        "Bio-essence 碧歐斯",
        "LA ROCHE-POSAY 理膚寶水",
        "TONYMOLY",
        "Derma Formula 美肌醫生",
        "法國歐德瑪",
        "Skinfood",
        "BEAUTIA 倍立雅",
        "NARUKO",
        "Beautymate 美肌之誌",
        "Collagen",
        "SwissVita 瑞士薇佳",
        "L'EGERE 蘭吉兒",
        "Jericho",
        "SYRIO",
        "VICHY 薇姿",
        "Sulwhasoo 雪花秀",
        "Domohorn Wrinkle 朵茉麗蔻",
        "nooni",
        "Valmont 法兒曼",
        "AYURA 東洋美學"
    ],
    "粉底液": [
        "media 媚點",
        "ettusais 艾杜紗",
        "MUJI 無印良品",
        "MAJOLICA MAJORCA 戀愛魔鏡",
        "KATE 凱婷",
        "Les Merveilleuses LADUREE",
        "L'OREAL PARIS 巴黎萊雅",
        "UNT",
        "SOFINA 蘇菲娜",
        "INTEGRATE 絕色魅癮",
        "Mdmmd. 明洞國際",
        "A'PIEU",
        "ZA",
        "Absolute New York 絕色紐約",
        "奢華寶貝",
        "I’M MEME",
        "NACOLA",
        "REVLON 露華濃",
        "MAYBELLINE 媚比琳",
        "BOURJOIS 妙巴黎",
        "BeautyMaker",
        "1028"
    ],
    "身體防曬": [
        "ettusais 艾杜紗",
        "FRUSIRNANA 美膚娜娜",
        "KOSE COSMEPORT 蔻絲魅寶",
        "專科",
        "NEUTROGENA 露得清",
        "FASIO 菲希歐"
    ],
    "唇彩唇蜜": [
        "MISSHA",
        "eSpoir",
        "heme",
        "media 媚點",
        "MAJOLICA MAJORCA 戀愛魔鏡",
        "banila co.",
        "KATE 凱婷",
        "BEYOND",
        "AZPLAZA",
        "L'OREAL PARIS 巴黎萊雅",
        "SOFINA 蘇菲娜",
        "INTEGRATE 絕色魅癮",
        "3CE",
        "A'PIEU",
        "CHATEAU LABIOTTE",
        "PALTAC",
        "ZA",
        "CANMAKE",
        "BBIA",
        "Absolute New York 絕色紐約",
        "奢華寶貝",
        "I’M MEME",
        "NACOLA",
        "REVLON 露華濃",
        "MAYBELLINE 媚比琳",
        "L'EGERE 蘭吉兒",
        "BOURJOIS 妙巴黎",
        "Solone",
        "CLIO 珂莉奧",
        "Peripera",
        "BeautyMaker",
        "Mistine",
        "1028",
        "FASIO 菲希歐"
    ],
    "美胸保養": [
        "webner 葦柏納"
    ],
    "氣墊粉餅": [
        "MISSHA",
        "Dr. Jart+",
        "APRIL SKIN",
        "CHICA Y CHICO",
        "banila co.",
        "BEYOND",
        "L'OREAL PARIS 巴黎萊雅",
        "UNT",
        "A'PIEU",
        "ZA",
        "MEMEBOX",
        "IOPE",
        "MAYBELLINE 媚比琳",
        "KISS ME 奇士美",
        "L'EGERE 蘭吉兒",
        "N.A.F",
        "CLIO 珂莉奧",
        "J.ONE",
        "Sulwhasoo 雪花秀",
        "moonshot",
        "KAI DELUXE 型色大師",
        "BeautyMaker",
        "1028"
    ],
    "頭皮養護": [
        "TSUBAKI 思波綺",
        "Rene Furterer 荷那法蕊"
    ],
    "遮瑕": [
        "media 媚點",
        "YourHeart",
        "WONDER CORE",
        "banila co.",
        "KATE 凱婷",
        "ESSENCE",
        "INTEGRATE 絕色魅癮",
        "A'PIEU",
        "ZA",
        "CANMAKE",
        "Absolute New York 絕色紐約",
        "I’M MEME",
        "CEZANNE",
        "REVLON 露華濃",
        "MAYBELLINE 媚比琳",
        "L'EGERE 蘭吉兒",
        "BOURJOIS 妙巴黎",
        "N.A.F",
        "VICHY 薇姿",
        "CLIO 珂莉奧",
        "Sulwhasoo 雪花秀",
        "1028",
        "PONY EFFECT"
    ],
    "眉彩": [
        "MISSHA",
        "media 媚點",
        "MAJOLICA MAJORCA 戀愛魔鏡",
        "neuve 惹我",
        "KATE 凱婷",
        "AZPLAZA",
        "L'OREAL PARIS 巴黎萊雅",
        "UNT",
        "INTEGRATE 絕色魅癮",
        "A'PIEU",
        "PALTAC",
        "ZA",
        "CANMAKE",
        "BBIA",
        "Absolute New York 絕色紐約",
        "Reinachu 日本蕾娜啾",
        "奢華寶貝",
        "I’M MEME",
        "CEZANNE",
        "NACOLA",
        "K-PALETTE",
        "REVLON 露華濃",
        "MAYBELLINE 媚比琳",
        "KISS ME 奇士美",
        "VDL",
        "BOURJOIS 妙巴黎",
        "N.A.F",
        "Solone",
        "CLIO 珂莉奧",
        "Peripera",
        "Mistine",
        "1028",
        "FASIO 菲希歐"
    ],
    "身體去角質": [
        "dermalogica 德卡",
        "PURE"
    ],
    "指甲油": [
        "UNT",
        "INTEGRATE 絕色魅癮",
        "MAYBELLINE 媚比琳"
    ],
    "彩妝工具": [
        "heme",
        "MAYBELLINE 媚比琳",
        "PONY EFFECT"
    ],
    "美甲保養": [
        "INTEGRATE 絕色魅癮"
    ],
    "腮紅修容": [
        "MISSHA",
        "heme",
        "media 媚點",
        "ettusais 艾杜紗",
        "MAJOLICA MAJORCA 戀愛魔鏡",
        "banila co.",
        "KATE 凱婷",
        "AZPLAZA",
        "L'OREAL PARIS 巴黎萊雅",
        "SOFINA 蘇菲娜",
        "INTEGRATE 絕色魅癮",
        "A'PIEU",
        "ANIMECOSME",
        "ZA",
        "CANMAKE",
        "BBIA",
        "Absolute New York 絕色紐約",
        "I’M MEME",
        "too cool for school",
        "CEZANNE",
        "REVLON 露華濃",
        "MAYBELLINE 媚比琳",
        "VDL",
        "L'EGERE 蘭吉兒",
        "BOURJOIS 妙巴黎",
        "Solone",
        "Peripera",
        "Sulwhasoo 雪花秀",
        "BeautyMaker",
        "Mistine",
        "1028",
        "FASIO 菲希歐",
        "Biore 蜜妮",
        "PONY EFFECT"
    ],
    "臉部去角質": [
        "heme",
        "ettusais 艾杜紗",
        "Dr.Morita 森田藥粧",
        "Institut Karite Paris 巴黎乳油木",
        "Dr.Organic",
        "NEOGENCE 霓淨思",
        "BIONIKE",
        "CNP LABORATORY",
        "St.Clare 聖克萊爾",
        "webner 葦柏納",
        "Dr.Satin",
        "ZA",
        "STIVES 聖艾芙",
        "BEAUTIA 倍立雅",
        "NARUKO",
        "Reme+G 潤美肌",
        "VICHY 薇姿",
        "LOVECODE"
    ],
    "保養工具": [
        "GATSBY",
        "3M",
        "俏佳人",
        "Avene 雅漾",
        "banila co.",
        "bonvivant",
        "NEOGENCE 霓淨思",
        "Panatec 沛莉緹",
        "COTA",
        "Love Ways 羅崴詩",
        "Clean & Clear 可伶可俐",
        "too cool for school",
        "WATSONSSKIN 屈臣氏",
        "MENTHOLATUM 曼秀雷敦",
        "LOVECODE",
        "Biore 蜜妮",
        "AYURA 東洋美學"
    ],
    "身體保養": [
        "babaria 西班牙babaria",
        "Kamill",
        "Avene 雅漾",
        "專科",
        "Institut Karite Paris 巴黎乳油木",
        "NEOGENCE 霓淨思",
        "UNT",
        "Curel 珂潤",
        "Cellina 雪芙蘭",
        "EVOLU 艾芙洛",
        "Bioderma 法國貝德瑪",
        "Johnson's 嬌生",
        "LA ROCHE-POSAY 理膚寶水",
        "dermalogica 德卡",
        "pHisoDerm 菲蘇德美",
        "Vaseline 凡士林"
    ],
    "擴香": [
        "Skinfood"
    ],
    "蜜粉": [
        "MISSHA",
        "media 媚點",
        "ettusais 艾杜紗",
        "TKY",
        "MAJOLICA MAJORCA 戀愛魔鏡",
        "banila co.",
        "KATE 凱婷",
        "AZPLAZA",
        "UNT",
        "Curel 珂潤",
        "SOFINA 蘇菲娜",
        "INTEGRATE 絕色魅癮",
        "Freshel 膚蕊",
        "ANIMECOSME",
        "FITIT&WHITIA",
        "CEZANNE",
        "REVLON 露華濃",
        "MAYBELLINE 媚比琳",
        "Srichand 喜簪",
        "L'EGERE 蘭吉兒",
        "BOURJOIS 妙巴黎",
        "Sulwhasoo 雪花秀",
        "BeautyMaker",
        "1028"
    ],
    "保養面膜": [
        "MISSHA",
        "Hada-Labo 肌研",
        "For Beloved Girl 寵愛女孩",
        "廣源良",
        "Dr.Morita 森田藥粧",
        "ettusais 艾杜紗",
        "FRUSIRNANA 美膚娜娜",
        "FASHION K-BEAUTY",
        "PINKGOGIRL Hey！蘋果肌女孩",
        "Dr. Jart+",
        "Avene 雅漾",
        "FORENCOS",
        "KOSE COSMEPORT 蔻絲魅寶",
        "La Formule 法國植萃合度",
        "innisfree",
        "50惠",
        "CLEAR TURN",
        "divinia 蒂芬妮亞",
        "Institut Karite Paris 巴黎乳油木",
        "banila co.",
        "bonvivant",
        "Whoo 后",
        "GARNIER 卡尼爾",
        "我的美麗日記",
        "NEOGENCE 霓淨思",
        "CHRONO AFFECTION 時間寵愛",
        "L'OREAL PARIS 巴黎萊雅",
        "CHLITINA 克麗緹娜",
        "UNT",
        "SKINBIOTEC 肌研生醫",
        "NEUTROGENA 露得清",
        "MYSCHEMING 我的心機",
        "Cellina 雪芙蘭",
        "JINGCHENG 京城之霜",
        "MEGUSTAME 美愛美",
        "WHITE FORMULA 自白肌",
        "CNP LABORATORY",
        "SWEETHEARTBEAUTY 甜心美妝",
        "DR.BRONNER’S 布朗博士",
        "coni beauty",
        "TSAIO 上山採藥",
        "HIKARU 喜凱露",
        "webner 葦柏納",
        "am+pm skincare",
        "美舒律",
        "OLAY 歐蕾",
        "ANIMECOSME",
        "Dr.Satin",
        "Bio-essence 碧歐斯",
        "LA ROCHE-POSAY 理膚寶水",
        "SISTERDIARY 姊妹日記",
        "VALENTINO 范倫鐵諾",
        "dermalogica 德卡",
        "Mori 水漾膜麗",
        "ZBYZIVA",
        "BEAUTIA 倍立雅",
        "NARUKO",
        "Beautymate 美肌之誌",
        "Reme+G 潤美肌",
        "TEAPOWER 茶寶",
        "NACOLA",
        "L&P MEDIHEAL 美迪惠爾",
        "FOR BELOVED ONE 寵愛之名",
        "Face Queen 絕世愛美肌",
        "KISS ME 奇士美",
        "SwissVita 瑞士薇佳",
        "DERMAL",
        "PURE SMILE",
        "OGUMA 水美媒",
        "Jericho",
        "VICHY 薇姿",
        "Sulwhasoo 雪花秀",
        "Beauty Buffet 天天美麗",
        "BONANZA 寶藝",
        "WATSONSSKIN 屈臣氏",
        "ELE",
        "HARMONY",
        "1028",
        "Valmont 法兒曼",
        "LULULUN",
        "LOVECODE",
        "Biore 蜜妮"
    ],
    "洗顏產品": [
        "MISSHA",
        "Hada-Labo 肌研",
        "廣源良",
        "ettusais 艾杜紗",
        "3M",
        "NIVEA 妮維雅",
        "VOO DOO",
        "HACCI",
        "Dr.Morita 森田藥粧",
        "CHAPEX 喬沛詩",
        "Dr. Jart+",
        "Avene 雅漾",
        "CETAPHIL 舒特膚",
        "KOSE COSMEPORT 蔻絲魅寶",
        "BECUPIDON 邱比特",
        "專科",
        "THE FACE SHOP 菲詩小舖",
        "divinia 蒂芬妮亞",
        "Country & Stream",
        "80",
        "SHISEIDO 資生堂（開架式）",
        "PALMER'S 帕瑪氏",
        "bonvivant",
        "GARNIER 卡尼爾",
        "NEOGENCE 霓淨思",
        "CHRONO AFFECTION 時間寵愛",
        "L'OREAL PARIS 巴黎萊雅",
        "Dove 多芬",
        "BIONIKE",
        "CHLITINA 克麗緹娜",
        "UNT",
        "Curel 珂潤",
        "SOFINA 蘇菲娜",
        "NEUTROGENA 露得清",
        "DHC",
        "MEGUSTAME 美愛美",
        "POND'S 旁氏",
        "Bioderma 法國貝德瑪",
        "WHITE FORMULA 自白肌",
        "CNP LABORATORY",
        "ORBIS",
        "DR.BRONNER’S 布朗博士",
        "Goat",
        "TSAIO 上山採藥",
        "webner 葦柏納",
        "DCS",
        "am+pm skincare",
        "Freshel 膚蕊",
        "AQUA LABEL 水之印",
        "FITIT&WHITIA",
        "Dr.Satin",
        "ZA",
        "AVALON",
        "Bio-essence 碧歐斯",
        "LA ROCHE-POSAY 理膚寶水",
        "uno",
        "TONYMOLY",
        "EVITA 艾薇塔",
        "Clean & Clear 可伶可俐",
        "dermalogica 德卡",
        "Reinachu 日本蕾娜啾",
        "法國歐德瑪",
        "Pure Beauty",
        "奢華寶貝",
        "NARUKO",
        "Marykay 玫琳凱",
        "SKINLIFE 滋卿愛",
        "Thailand bird's 泰國雙燕",
        "ROSYROSA",
        "DR.WU 達爾膚",
        "Collagen",
        "SwissVita 瑞士薇佳",
        "philosophy 肌膚哲理",
        "Jericho",
        "Softymo 絲芙蒂",
        "VICHY 薇姿",
        "Peripera",
        "pHisoDerm 菲蘇德美",
        "Rudy Profumi",
        "BONANZA 寶藝",
        "MENTHOLATUM 曼秀雷敦",
        "alkmene",
        "HARMONY",
        "nooni",
        "1028",
        "Valmont 法兒曼",
        "BENZAC",
        "Revlis",
        "Biore 蜜妮"
    ],
    "手部清潔": [
        "Marykay 玫琳凱"
    ],
    "清潔面膜": [
        "廣源良",
        "FRUSIRNANA 美膚娜娜",
        "FASHION K-BEAUTY",
        "PETALFRESH 沛特斯",
        "Dr. Jart+",
        "FORENCOS",
        "GHOSTTOWASH",
        "KOSE COSMEPORT 蔻絲魅寶",
        "APRIL SKIN",
        "divinia 蒂芬妮亞",
        "bonvivant",
        "Whoo 后",
        "Dr.Organic",
        "NEOGENCE 霓淨思",
        "THE BODY SHOP 美體小舖",
        "webner 葦柏納",
        "am+pm skincare",
        "STIVES 聖艾芙",
        "too cool for school",
        "Reme+G 潤美肌",
        "Jericho",
        "Beauty Buffet 天天美麗",
        "BONANZA 寶藝",
        "MENTHOLATUM 曼秀雷敦",
        "LOVECODE",
        "Biore 蜜妮"
    ],
    "女性香氛": [
        "banila co.",
        "Skinfood"
    ],
    "粉條": [

    ]
}

PRODUCT_COLOR = {
    "眉彩": [
        "自然棕",
        "自然深棕",
        "自然紅棕",
        "自然黑",
        "咖啡色",
        "棕",
        "深棕",
        "灰",
        "黑",
        "明亮棕",
        "NOCOLOR",
        "棕色",
        "灰色",
        "深棕色",
        "淺棕色",
        "深灰色",
        "亞麻色",
        "灰褐色",
        "紅棕色"
    ],
    "美胸保養": [
        "NOCOLOR"
    ],
    "精華液": [
        "NOCOLOR"
    ],
    "唇彩唇蜜": [
        "粉色",
        "粉紅色",
        "橘色/裸色",
        "蜜桃玫瑰",
        "黑",
        "玫瑰色",
        "紅色",
        "橘色",
        "裸色",
        "透明",
        "桃紅色",
        "酒紅色",
        "NOCOLOR"
    ],
    "指甲油": [
        "NOCOLOR"
    ],
    "唇部保養": [
        "NOCOLOR"
    ],
    "護髮品": [
        "NOCOLOR"
    ],
    "頭皮養護": [
        "NOCOLOR"
    ],
    "彩妝工具": [
        "NOCOLOR"
    ],
    "眼部保養": [
        "NOCOLOR"
    ],
    "臉部去角質": [
        "NOCOLOR"
    ],
    "蜜粉": [
        "明亮膚色",
        "自然膚色",
        "透明",
        "暖色",
        "NOCOLOR"
    ],
    "女性香氛": [
        "NOCOLOR"
    ],
    "化妝水": [
        "NOCOLOR"
    ],
    "睫毛膏": [
        "NOCOLOR",
        "光澤黑",
        "黑",
        "紅"
    ],
    "爽身制汗品": [
        "NOCOLOR"
    ],
    "眼唇卸妝": [
        "NOCOLOR"
    ],
    "乳霜": [
        "NOCOLOR"
    ],
    "粉餅": [
        "明亮膚色",
        "亮膚色",
        "自然膚色",
        "健康膚色",
        "柔膚色",
        "粉膚色",
        "NOCOLOR"
    ],
    "美甲保養": [
        "NOCOLOR"
    ],
    "擴香": [
        "NOCOLOR"
    ],
    "保養面膜": [
        "NOCOLOR"
    ],
    "BB霜": [
        "自然膚色",
        "明亮膚色",
        "白皙膚色",
        "粉膚色",
        "亮膚色",
        "柔膚色",
        "健康膚色",
        "NOCOLOR"
    ],
    "妝前打底": [
        "粉綠色",
        "透白膚色",
        "水蜜桃膚色",
        "綠色",
        "橘色",
        "粉膚色",
        "NOCOLOR",
        "粉",
        "金色",
        "粉色",
        "白色"
    ],
    "身體防曬": [
        "NOCOLOR"
    ],
    "保養工具": [
        "NOCOLOR"
    ],
    "遮瑕": [
        "明亮膚色",
        "自然膚色",
        "NOCOLOR",
        "明亮膚",
        "自然膚"
    ],
    "乳液": [
        "NOCOLOR"
    ],
    "唇膏": [
        "桃紅色",
        "粉色",
        "橘色",
        "酒紅色",
        "紅色",
        "裸色",
        "玫瑰色",
        "橘紅色",
        "粉紅色",
        "紫色",
        "莓紅",
        "杏桃",
        "裸粉",
        "粉紅",
        "橘粉",
        "玫紅",
        "伯爵奶茶",
        "杏桃甜心",
        "搖滾桃紅",
        "熱戀玫瑰",
        "酒紅",
        "大地色",
        "裸色大地色",
        "NOCOLOR",
        "莓紅色",
        "橘桃色"
    ],
    "身體保養": [
        "NOCOLOR"
    ],
    "保濕噴霧": [
        "NOCOLOR"
    ],
    "洗顏產品": [
        "NOCOLOR"
    ],
    "潤髮品": [
        "NOCOLOR"
    ],
    "勻體緊實產品": [
        "NOCOLOR"
    ],
    "腮紅修容": [
        "玫瑰色",
        "粉色",
        "桃紅色",
        "淺棕",
        "深棕",
        "蜜桃玫瑰",
        "粉紅",
        "NOCOLOR",
        "橘色",
        "粉紅色",
        "紅色",
        "黃色"
    ],
    "粉底液": [
        "粉膚色",
        "柔膚色",
        "亮膚色",
        "健康膚色",
        "明亮膚色",
        "自然膚色",
        "NOCOLOR"
    ],
    "眼影": [
        "粉紅色",
        "粉色",
        "裸色",
        "大地棕",
        "粉紅",
        "酒紅",
        "棕色",
        "淺棕色",
        "深棕色",
        "綠",
        "藍",
        "紫",
        "NOCOLOR",
        "栗子棕",
        "咖啡色"
    ],
    "手部保養": [
        "NOCOLOR"
    ],
    "凝膠凝凍": [
        "NOCOLOR"
    ],
    "男仕臉部保養": [
        "NOCOLOR"
    ],
    "身體去角質": [
        "NOCOLOR"
    ],
    "洗髮品": [
        "NOCOLOR"
    ],
    "男仕刮鬍護理": [
        "NOCOLOR"
    ],
    "卸妝產品": [
        "NOCOLOR"
    ],
    "氣墊粉餅": [
        "白皙",
        "明亮膚色",
        "白皙色",
        "NOCOLOR",
        "自然膚色"
    ],
    "髮妝造型": [
        "NOCOLOR"
    ],
    "前導保養": [
        "NOCOLOR"
    ],
    "眼線": [
        "深棕色",
        "棕色",
        "金色",
        "紅色",
        "黑色",
        "鑽黑",
        "咖啡",
        "墨綠",
        "酒紅",
        "粉橘",
        "黑",
        "金棕",
        "濃黑",
        "自然黑",
        "自然棕",
        "NOCOLOR",
        "棕",
        "咖啡色",
        "紅棕"
    ],
    "手部清潔": [
        "NOCOLOR"
    ],
    "私密處護理": [
        "NOCOLOR"
    ],
    "粉霜": [
        "NOCOLOR"
    ],
    "腿足保養": [
        "NOCOLOR"
    ],
    "CC霜": [
        "自然",
        "明亮",
        "NOCOLOR",
        "粉紅",
        "綠",
        "明亮膚色",
        "自然膚色"
    ],
    "精華油": [
        "NOCOLOR"
    ],
    "清潔面膜": [
        "NOCOLOR"
    ],
    "唇筆": [
        "玫瑰色",
        "粉色",
        "紅色",
        "橘色",
        "裸色",
        "NOCOLOR"
    ],
    "身體清潔": [
        "NOCOLOR"
    ],
    "防曬隔離": [
        "膚色",
        "NOCOLOR",
        "自然膚色"
    ],
    "粉條": [

    ]
}
